/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ModeloDto;

/**
 *
 * @author ULISES.VIEYRA
 */
public class ScriptGenerado {
    /*
   -- MySQL Script generated by MySQL Workbench
-- Mon Sep 14 14:06:43 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistemabd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistemabd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistemabd` DEFAULT CHARACTER SET utf8 ;
USE `sistemabd` ;

-- -----------------------------------------------------
-- Table `sistemabd`.`tc_usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemabd`.`tc_usuarios` ;

CREATE TABLE IF NOT EXISTS `sistemabd`.`tc_usuarios` (
  `IdUsuario` INT NOT NULL AUTO_INCREMENT,
  `Nombres` VARCHAR(45) NULL,
  `Apellidos` VARCHAR(45) NULL,
  `Celular` VARCHAR(45) NULL,
  `Correo` VARCHAR(45) NULL,
  `FechaDeNacimiento` DATE NULL,
  `FechaDeAlta` DATE NULL,
  `Activo` TINYINT NULL,
  `Usuario` VARCHAR(45) NULL,
  `IdPerfil` INT NULL,
  `Domicilio` VARCHAR(45) NULL,
  `Estado` VARCHAR(45) NULL,
  `Municipio` VARCHAR(45) NULL,
  `Pais` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  PRIMARY KEY (`IdUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemabd`.`tc_cuestionarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemabd`.`tc_cuestionarios` ;

CREATE TABLE IF NOT EXISTS `sistemabd`.`tc_cuestionarios` (
  `IdCuestionario` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  `FechaDeAlta` DATE NULL,
  `Activo` TINYINT NULL,
  `TipoPregunta` INT NULL,
  PRIMARY KEY (`IdCuestionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemabd`.`tr_preguntas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemabd`.`tr_preguntas` ;

CREATE TABLE IF NOT EXISTS `sistemabd`.`tr_preguntas` (
  `IdPregunta` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NULL,
  `IdCuestionario` INT NULL,
  `Orden` INT NULL,
  `Activo` TINYINT NULL,
  `FechaDeAlta` DATE NULL,
  `IdUsuario` INT NULL,
  PRIMARY KEY (`IdPregunta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemabd`.`tr_respuestas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemabd`.`tr_respuestas` ;

CREATE TABLE IF NOT EXISTS `sistemabd`.`tr_respuestas` (
  `idRespuesta` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NULL,
  `IdPaciente` INT NULL,
  `FechaDeAlta` DATE NULL,
  PRIMARY KEY (`idRespuesta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemabd`.`tc_tiposDePregunta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemabd`.`tc_tiposDePregunta` ;

CREATE TABLE IF NOT EXISTS `sistemabd`.`tc_tiposDePregunta` (
  `IdTipoDePregunta` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NULL,
  `Activo` TINYINT NULL,
  `FechaDeAlta` DATE NULL,
  `IdUsuario` INT NULL,
  PRIMARY KEY (`IdTipoDePregunta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemabd`.`tc_tratamientos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemabd`.`tc_tratamientos` ;

CREATE TABLE IF NOT EXISTS `sistemabd`.`tc_tratamientos` (
  `IdTratamiento` INT NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Activo` TINYINT NULL,
  `FechaDeAlta` DATE NULL,
  `Precio` FLOAT NULL,
  `IdUsuario` INT NULL,
  PRIMARY KEY (`IdTratamiento`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `sistemabd`.`tc_perfiles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemabd`.`tc_perfiles` ;

CREATE TABLE IF NOT EXISTS `sistemabd`.`tc_perfiles` (
  `IdPerfil` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Activo` TINYINT NULL,
  `FechaDeAlta` DATE NULL,
  `IdUsuario` INT NULL,
  PRIMARY KEY (`IdPerfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemabd`.`tc_menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemabd`.`tc_menu` ;

CREATE TABLE IF NOT EXISTS `sistemabd`.`tc_menu` (
  `IdMenu` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Controlador` VARCHAR(45) NULL,
  `Activo` TINYINT NULL,
  `FechaDeAlta` VARCHAR(45) NULL,
  `IdUsuario` INT NULL,
  PRIMARY KEY (`IdMenu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemabd`.`tr_permisos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemabd`.`tr_permisos` ;

CREATE TABLE IF NOT EXISTS `sistemabd`.`tr_permisos` (
  `IdPermiso` INT NOT NULL,
  `IdPerfil` INT NULL,
  `IdMenu` INT NULL,
  `FechaDeAlta` VARCHAR(45) NULL,
  `IdUsuario` VARCHAR(45) NULL,
  PRIMARY KEY (`IdPermiso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemabd`.`tc_tipoDescuento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemabd`.`tc_tipoDescuento` ;

CREATE TABLE IF NOT EXISTS `sistemabd`.`tc_tipoDescuento` (
  `IdTipoDescuento` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  `FechaDeAlta` DATE NULL,
  `IdUsuario` VARCHAR(45) NULL,
  `Activo` TINYINT NULL,
  PRIMARY KEY (`IdTipoDescuento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemabd`.`tr_presupuestos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemabd`.`tr_presupuestos` ;

CREATE TABLE IF NOT EXISTS `sistemabd`.`tr_presupuestos` (
  `IdPresupuesto` INT NOT NULL,
  `IdPaciente` INT NULL,
  `IdTratamiento` INT NULL,
  `IdTipoDescuento` INT NULL,
  `Precio` FLOAT NULL,
  `FechaDeAlta` DATE NULL,
  `IdDoctor` INT NULL,
  `IdUsuario` INT NULL,
  PRIMARY KEY (`IdPresupuesto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemabd`.`tr_ordenDeTrabajo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemabd`.`tr_ordenDeTrabajo` ;

CREATE TABLE IF NOT EXISTS `sistemabd`.`tr_ordenDeTrabajo` (
  `IdOrdenDeTrabajo` INT NOT NULL,
  `IdPaciente` INT NULL,
  `IdTratamiento` INT NULL,
  `IdTipoDescuento` INT NULL,
  `Precio` FLOAT NULL,
  `FechaDeAlta` DATE NULL,
  `IdDoctor` INT NULL,
  `IdUsuario` INT NULL,
  `IdCompra` INT NULL,
  PRIMARY KEY (`IdOrdenDeTrabajo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemabd`.`tr_compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemabd`.`tr_compras` ;

CREATE TABLE IF NOT EXISTS `sistemabd`.`tr_compras` (
  `IdCompra` INT NOT NULL,
  `FechaDeAlta` DATE NULL,
  `Total` FLOAT NULL,
  `IdUsuario` INT NULL,
  `IdDoctor` INT NULL,
  `IdEstadoCompra` INT NULL,
  PRIMARY KEY (`IdCompra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemabd`.`tc_estadoCompra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemabd`.`tc_estadoCompra` ;

CREATE TABLE IF NOT EXISTS `sistemabd`.`tc_estadoCompra` (
  `IdEstadoCompra` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Activo` TINYINT NULL,
  `FechaDeAlta` DATE NULL,
  `IdUsuario` INT NULL,
  PRIMARY KEY (`IdEstadoCompra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemabd`.`tr_abonos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemabd`.`tr_abonos` ;

CREATE TABLE IF NOT EXISTS `sistemabd`.`tr_abonos` (
  `IdAbono` INT NOT NULL,
  `FechaDeAlta` DATE NULL,
  `Cantidad` FLOAT NULL,
  `IdUsuario` INT NULL,
  `IdCompra` INT NULL,
  PRIMARY KEY (`IdAbono`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemabd`.`tr_citas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemabd`.`tr_citas` ;

CREATE TABLE IF NOT EXISTS `sistemabd`.`tr_citas` (
  `IdCita` INT NOT NULL,
  `FechaDeAlta` DATE NULL,
  `FechaDeCita` DATE NULL,
  `HoraDeCita` VARCHAR(45) NULL,
  `Activo` TINYINT NULL,
  `IdPaciente` INT NULL,
  `IdUsuario` INT NULL,
  `IdEstadoDeCita` INT NULL,
  `IdDoctor` INT NULL,
  PRIMARY KEY (`IdCita`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemabd`.`tc_estadosDeCita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemabd`.`tc_estadosDeCita` ;

CREATE TABLE IF NOT EXISTS `sistemabd`.`tc_estadosDeCita` (
  `IdEstadoDeCita` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Activo` TINYINT NULL,
  `IdUsuario` INT NULL,
  `FechaDeAlta` DATE NULL,
  PRIMARY KEY (`IdEstadoDeCita`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
  */
    
}
